# Generated by Django 4.2.1 on 2023-05-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='gen',
            field=models.CharField(default='Thriller', max_length=250),
            preserve_default=False,
        ),
    ]
